modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="redstone_armor_and_tools"
version="9.9.9"
displayName="Redstone Armor and Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="An12854"
description='''
Another redstone armor mod for Minecraft 1.16.5
'''

[[dependencies.redstone_armor_and_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




